### ISSUE TITLE
may i have your attention?

### ISSUE THREAD

**Issue by MikeoPerfect** [KIM-JS-95/CutLinePages#1]
hi sir, may i have your attention please, your application.properties is exposed and the mysql's passwd is opened, I hope it won't make you uncomfortable

**Comment by KIM-JS-95** [comment]
Thank you Mikeo!!

I am going to check that problem!

> hi sir, may i have your attention please, your application.properties is exposed and the mysql's passwd is opened, I hope it won't make you uncomfortable
